services:
  etudiant-db-service:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etudiant_db
    networks:
      - etudiant-net

networks:
  etudiant-net:
    driver: bridge

volumes:
  postgres: